# 프로젝트 Root 폴더
# 프로젝트Root/docker-compose.yml
version: '3.7'

services:
  frontend:
    container_name: "alphagom_frontend"
    image: alphagom_frontend:0.1
    build:
      context: Front/alphagom/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    # [인증서 파일 저장 경로]:/root
    volumes:
      - /etc/letsencrypt/live/j7d210.p.ssafy.io/:/root
    environment:
      - TZ=Asia/Seoul
